### PR TITLE
Fix bad offset management

### LINKED ISSUE #380: Investigate offset management
We should investigate if we need offset management when using vertx kafka client and web client which are async.

## Additional Info

- https://github.com/strimzi/strimzi-kafka-bridge/blob/d782d3ff87edd7e47cdf2c87d480c26cbf8a87d5/src/main/java/io/strimzi/kafka/bridge/SinkBridgeEndpoint.java#L62-L63
- https://github.com/strimzi/strimzi-kafka-bridge/blob/b9fd6b7b462dfa7c08add87a3875a33f8887a522/src/main/java/io/strimzi/kafka/bridge/tracker/SimpleOffsetTracker.java
- https://github.com/strimzi/strimzi-kafka-bridge/blob/b9fd6b7b462dfa7c08add87a3875a33f8887a522/src/main/java/io/strimzi/kafka/bridge/tracker/FullOffsetTracker.java

- https://console.cloud.google.com/storage/browser/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/369/pull-knative-sandbox-eventing-kafka-broker-integration-tests/1323232785825009664/artifacts/98a01d98-1d02-11eb-9b07-ba5e5d672405/knative-eventing-logs/knative-eventing?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&forceOnObjectsSortingFiltering=false

- https://00f74ba44b1d15b084db7ed9df0f0e1f2dfe42897b-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/pr-logs%2Fpull%2Fknative-sandbox_eventing-kafka-broker%2F369%2Fpull-knative-sandbox-eventing-kafka-broker-integration-tests%2F1323232785825009664%2Fartifacts%2F98a01d98-1d02-11eb-9b07-ba5e5d672405%2Fknative-eventing-logs%2Fknative-eventing%2Fkafka-broker-dispatcher-6d8d7964df-ssjwv-kafka-broker-dispatcher.log?jk=AFshE3WkEVySZQ7MGl3RPRyYcEwK_GPt7oXd_v3aQapaubt6kBAbKwaHB35YkMv-jEXVtGYfVlJQpzvXJ8JDlITgFsf1qAZVaASPlA_zdbafWOU1UONHSX3fZhBbOPrEE-_vBXFEeh--JNu35yjndtxNEZvkG1ois4N4KSbt_YjryesKdrL9esLk4_wEEAH217BTz5HMuNsl6rHWC9AXM-Y96qF5bp2my5amQGEI3zvblgyqVRPA38APjV91NAlb30V34fo6UFU_OPtCgwz1JcbuyTPMurayf1kdRadfrLdJbgFYlUaLzKVj5EdyXvl5NvV7gb81NH3kosNvFWhbEQN8cVDwDqDTjHNjxeqKd7PwcU_ndo5MTeSUZlEgHl8ggKoJKLy5BXdFVX0q3J2E3QkK1DkkEhfRJxRbyXAhHcyGEXWEPT4piEzzU3E1E-pBssOQxvPCKF3_dPhs6UgvWpCMytcmLN10n4kPCFooixBMgHiQD0d34wrDnRVKToA7yvFQNmRbYiW18F3O_il87lcBajPXVVR1F_O1crUv0fgXioyY5JxPMsQ4H9FrBJQCL3t6BlYBYqvGUw4H44XEp-V602w-t5SENYYQGTfDrNwPcXjhzdTX1qiB6MWvc352OhOeN0zfjF9Hrb1B3Tn_8EzaNjFAcC76UOzCAi7kVDEnobdLdGCydzulzbC3tzWaH_y0Q_iZezGHQq60tDInc8MSZELBJAA4_VDdkF8Pdvadm1Ggn1eNY2P65i5elHSHp8C4cE356T1QVb0piPnpneOjYny40vt92TRtupORTvOQRBStNZSR_Cy_rC9sWyTms_L9RmTU6ixk0JebLSCeJu260tpSpGM-pzVUuZATZFJ-0ZhZMxBMdJ_6SjbNBWBSsHbnv9mIzg2gmvUI8XYwqFdr8ao4PmQjGqhF0CUioK4QkQ3BCPOLxZ6FQWqcgd-N21QPO5XRDDYbfYUwmAgft-QvJ2s7S_L3cMt8GbkfFFEuCsOsCyWRr-AJXG7by05BNevQwIIgGYIOftSpKHTk7QOK9xM9iYcc2AmDKfVO3W0SWBO4Nj_uVWRu78AUgm63aWN4DTn8tHmaxwT0fNNCB9LUkAMZ5TxR5ZUFUFWB-LAP-3keh_EjSReMTVGCWwIJqe22QJfDUqIISjKQ_W_46nTklZgVtRIVsmgbDS5-zoIvym6jfPO9FThKhgYcU8rwebqTECH9zTpGhjDQo_He3QhRKcvvZ4WEmiLLfjHPFtmgPQz_RXxhX_D9f30OaZQ&isca=1

/assign @slinkydeveloper

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Fixes #380

## Proposed Changes

- :bug: Now offset management is correct

**Release Note**

```release-note
:bug: Now offset management is correct
```

**Docs**

### CODE REVIEW

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 1]
```diff
@@ -57,64 +66,98 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+    commit(record);
   }
 
   /**
    * {@inheritDoc}
    */
   @Override
   public void failedToSendToDLQ(final KafkaConsumerRecord<?, ?> record, final Throwable ex) {
-    // do not commit
+    // TODO what do we do with that?
```
Comment (slinkydeveloper) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:97]: IMO here we should commit, or at least we should modify the internal state of this class in a way such that on the next "successful message", it will be committed (aka adding this commit to the `pendingAcksMap`). Otherwise, on the topic partition of this record, no commit will ever be committed again.

Comment (pierDipi) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:97]: I agree we should update the internal state.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 2]
```diff
@@ -19,21 +19,28 @@
...
+/**
+ * This class implements the offset strategy that makes sure that, even unordered, the offset commit is ordered.
+ */
 public final class UnorderedConsumerRecordOffsetStrategy implements ConsumerRecordOffsetStrategy {
 
   private static final Logger logger = LoggerFactory
     .getLogger(UnorderedConsumerRecordOffsetStrategy.class);
 
+  private final Map<TopicPartition, Long> lastAckedMap;
+  private final Map<TopicPartition, SortedSet<Long>> pendingAcksMap;
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:43]: A little comment of what these are would help.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 3]
```diff
@@ -19,21 +19,28 @@
...
 
+/**
+ * This class implements the offset strategy that makes sure that, even unordered, the offset commit is ordered.
+ */
 public final class UnorderedConsumerRecordOffsetStrategy implements ConsumerRecordOffsetStrategy {
 
   private static final Logger logger = LoggerFactory
     .getLogger(UnorderedConsumerRecordOffsetStrategy.class);
 
+  private final Map<TopicPartition, Long> lastAckedMap;
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:42]:
```suggestion
  private final Map<TopicPartition, Long> lastAckByTopicPartition;
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 2 above)
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:43]:
```suggestion
  private final Map<TopicPartition, SortedSet<Long>> pendingAcksByTopicPartition;
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 4]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+    if (shouldAck != null) {
+      // Reset the state
+      long lastAckedBeforeThisOne = this.lastAckedMap.put(key, shouldAck);
+      SortedSet<Long> messagesImGoingToAck = this.pendingAcksMap.remove(key);
+
+      // Execute the actual commit
+      consumer.commit(Map.of(
+        key,
+        new OffsetAndMetadata(shouldAck + 1, ""))
+      ).onSuccess(ignored -> {
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:132]: `onSuccess` on a new line?

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 5]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+        eventsSentCounter.increment(messagesImGoingToAck.size());
+        logger.debug(
+          "committed {} {} {}",
+          keyValue("topic", record.topic()),
+          keyValue("partition", record.partition()),
+          keyValue("offset", shouldAck)
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:138]:
```suggestion
          keyValue("offset", shouldAck + 1)
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 6]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+                return actual;
+              }
+              return messagesImGoingToAck;
+            });
+          }
+          logger.error(
+            "failed to commit {} {} {}",
+            keyValue("topic", record.topic()),
+            keyValue("partition", record.partition()),
+            keyValue("offset", shouldAck),
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:159]:
```suggestion
            keyValue("offset", shouldAck + 1),
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 7]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+    SortedSet<Long> toAckSet = this.pendingAcksMap.computeIfAbsent(topicPartition, v -> new TreeSet<>());
+    toAckSet.add(offset);
+
+    return (toAckSet.first() == lastAckedOffset + 1 && toAckSet.last() - toAckSet.first() == toAckSet.size() - 1) ?
+      toAckSet.last() : null;
   }
+
+  private void commit(final KafkaConsumerRecord<?, ?> record) {
+    TopicPartition key = new TopicPartition(record.topic(), record.partition());
+    Long shouldAck = mutateStateAndCheckAck(key, record.offset());
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:122]:
```suggestion
    Long toAck = mutateStateAndCheckAck(key, record.offset());
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 8]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+    long lastAckedOffset = this.lastAckedMap.get(topicPartition); // This is always non null
+    SortedSet<Long> toAckSet = this.pendingAcksMap.computeIfAbsent(topicPartition, v -> new TreeSet<>());
+    toAckSet.add(offset);
+
+    return (toAckSet.first() == lastAckedOffset + 1 && toAckSet.last() - toAckSet.first() == toAckSet.size() - 1) ?
+      toAckSet.last() : null;
   }
+
+  private void commit(final KafkaConsumerRecord<?, ?> record) {
+    TopicPartition key = new TopicPartition(record.topic(), record.partition());
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:121]:
```suggestion
    TopicPartition topicPartition = new TopicPartition(record.topic(), record.partition());
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 9]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+          if (!(this.lastAckedMap.get(key) > shouldAck)) {
+            this.lastAckedMap.put(key, lastAckedBeforeThisOne);
+            this.pendingAcksMap.compute(key, (k, actual) -> {
+              if (actual != null) {
+                actual.addAll(messagesImGoingToAck);
+                return actual;
+              }
+              return messagesImGoingToAck;
+            });
+          }
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:154]: This needs some testing.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 10]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+          keyValue("topic", record.topic()),
+          keyValue("partition", record.partition()),
+          keyValue("offset", shouldAck)
+        );
+      })
+        .onFailure(cause -> {
+          // If the commit failed, there are 2 situations:
+          // * Nobody tried to commit again, so let's just restore the state
+          // * Somebody committed with an offset greater than this one, so we just discard the error
+          if (!(this.lastAckedMap.get(key) > shouldAck)) {
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:145]:
```suggestion
          if (this.lastAckedMap.get(key) <= shouldAck) {
```

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 11]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+  /**
+   * @return null if it shouldn't ack, otherwise the offset to ack - 1.
+   */
+  private Long mutateStateAndCheckAck(TopicPartition topicPartition, long offset) {
+    long lastAckedOffset = this.lastAckedMap.get(topicPartition); // This is always non null
+    SortedSet<Long> toAckSet = this.pendingAcksMap.computeIfAbsent(topicPartition, v -> new TreeSet<>());
+    toAckSet.add(offset);
+
+    return (toAckSet.first() == lastAckedOffset + 1 && toAckSet.last() - toAckSet.first() == toAckSet.size() - 1) ?
+      toAckSet.last() : null;
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:117]: It seems a good candidate for a comment or helper functions for named checks.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 12]
```diff
@@ -57,64 +66,101 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
   }
+
+  private void commit(final KafkaConsumerRecord<?, ?> record) {
+    TopicPartition key = new TopicPartition(record.topic(), record.partition());
+    Long shouldAck = mutateStateAndCheckAck(key, record.offset());
+    if (shouldAck != null) {
+      // Reset the state
+      long lastAckedBeforeThisOne = this.lastAckedMap.put(key, shouldAck);
+      SortedSet<Long> messagesImGoingToAck = this.pendingAcksMap.remove(key);
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:126]: This should be updated on success or on failure.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 4 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:132]: The closed paren is right there :smile:

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 2 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:43]: Ok I've added some comments and renamed the maps to be easier to understand

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 9 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:154]: It's already tested, check out `shouldCommitInAMixedOrderWithInducedFailure` and `shouldCommitAfterSendingEventsOrderedOnTheSamePartitionWithInducedFailure`

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 10 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:145]: No I want to keep it this way, since it's consistent with the above comment

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 12 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:126]: No, this is discarded in case of success, copy pasted in case of failure (if we actually need to restore the state)

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 9 above)
Comment (pierDipi) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java]: If I comment this code, tests are green. :confused:

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 13]
```diff
@@ -57,64 +71,106 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+        );
+      })
+        .onFailure(cause -> {
+          // If the commit failed, there are 2 situations:
+          // * Somebody committed with an offset greater than this one, so we just discard the error
+          // * Nobody tried to commit again, so let's restore the state
+          if (!(this.lastAckedPerPartition.get(topicPartition) > toAck)) {
+            this.lastAckedPerPartition.put(topicPartition, lastAckedBeforeThisOne);
+            this.pendingAcksPerPartition.compute(topicPartition, (k, actual) -> {
+              if (actual != null) {
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:158]: Is this possible since we call `mutateStateAndCheckAck` above?

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java [hunk 14]
```diff
@@ -57,64 +71,106 @@ public UnorderedConsumerRecordOffsetStrategy(final KafkaConsumer<?, ?> consumer,
...
+                actual.addAll(messagesImGoingToAck);
+                return actual;
+              }
+              return messagesImGoingToAck;
+            });
+          }
```
Comment (pierDipi) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:164]: If I comment out these lines, tests are green.

Comment (pierDipi) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:164]: Also, if we set the state on success, there is no need to rollback.

Comment (pierDipi) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:164]: It should be safer since the state could have changed since `lastAckedBeforeThisOne` was calculated.

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 13 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:158]: It is, because somebody could have asked meanwhile to add a new commit and that state could have been populated again

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java (hunk 14 above)
Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:164]: > If I comment out these lines, tests are green.

How could it be? Lemme check :thinking:

Comment (slinkydeveloper) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java:164]: Ah yes of course it goes green, but if the system crashes after the commit try, it will restart from the previous ack. Do we care?

**Review by pierDipi — APPROVED** [review]
/lgtm

Thank you!

/kind bug

**Comment by pierDipi** [comment]
Java tests failed with `Connection reset` in GH.
