### PR TITLE
Handle committing offsets on revoked partitions

### LINKED ISSUE #2176: Dispatcher pod logs unhandled exception during event consumption
**Describe the bug**
```

May 10, 2022 9:10:42 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException: Cannot invoke "dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager$OffsetTracker.recordNewOffset(long)" because the return value of "java.util.Map.get(Object)" is null
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.commit(OffsetManager.java:133)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.successfullySentToSubscriber(OffsetManager.java:103)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.onSubscriberSuccess(RecordDispatcherImpl.java:246)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.lambda$onFilterMatching$1(RecordDispatcherImpl.java:227)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda$null$4(CircuitBreakerImpl.java:232)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

 **Expected behavior**
This exception should not happen and when it happens, event consumption is halted. 

 **To Reproduce**
Send large amount of events to topic and and this should re-occur

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by pierDipi**
We need to handle the case when the offset tracker was removed from
our Map since when partitions are revoked we remove the associated
offset tracker, however, we may get a response from the sink for a
previously owned partition after a partition has been revoked.

Note: it's not possible to commit offsets of partitions that a
      particular consumer instance doesn't own.

I can't find a way to test this.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes #2176

### CODE REVIEW

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java [hunk 1]
```diff
@@ -128,9 +128,14 @@ public void recordDiscarded(final KafkaConsumerRecord<?, ?> record) {
...
   private void commit(final KafkaConsumerRecord<?, ?> record) {
-    this.offsetTrackers
-      .get(new TopicPartition(record.topic(), record.partition()))
-      .recordNewOffset(record.offset());
+    // We need to handle the case when the offset tracker was removed from our Map since when partitions are revoked we
+    // remove the associated offset tracker, however, we may get a response from the sink for a previously owned
+    // partition after a partition has been revoked.
+    // Note: it's not possible to commit offsets of partitions that this a particular consumer instance doesn't own.
+    final var ot = this.offsetTrackers.get(new TopicPartition(record.topic(), record.partition()));
+    if (ot != null) {
```
Comment (matzew) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java:136]: fluent APIs FTW :smile:

Comment (matzew) [reply data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java:136]: (and with `nil` returned)

**Review by matzew — APPROVED** [review]
/lgtm
/approve
