### PR TITLE
Do not block finalization if secret for external topic is gone

### LINKED ISSUE #2828: Broker deletion is stuck when the referenced secret is gone
If using a `auth.secret.ref.name` and if that referenced secret is gone (regardless how it was removed), the deletion of the broker is stuck:

```
k delete -f ./015-broker-with-config.yaml 
broker.eventing.knative.dev "my-broken-kafka-broker" deleted
configmap "my-broken-kafka-broker-config" deleted
```

Especially in cases with _external_ topics, we should be more lenient, if the secret is not present, and not block the finalization

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #2828

## Proposed Changes

- If secret for external managed topic is gone / not present, we do not block the finalization. The broker does anyways not need to perform any sorts of clean-ups on these externally managed topics

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

File: control-plane/pkg/reconciler/broker/broker.go [hunk 1]
```diff
@@ -387,14 +387,21 @@ func (r *Reconciler) finalizeKind(ctx context.Context, broker *eventing.Broker)
...
+			return nil
+		} else {
+			return fmt.Errorf("failed to get secret: %w", err)
+		}
 	}
 
 	// External topics are not managed by the broker,
 	// therefore we do not delete them
-	_, externalTopic := isExternalTopic(broker)
+	//	_, externalTopic := isExternalTopic(broker)
```
Comment (creydr) [inline control-plane/pkg/reconciler/broker/broker.go:404]: nit: remove line
```suggestion
```

File: control-plane/pkg/reconciler/broker/broker.go [hunk 2]
```diff
@@ -387,14 +387,21 @@ func (r *Reconciler) finalizeKind(ctx context.Context, broker *eventing.Broker)
 		return err
 	}
 
+	_, externalTopic := isExternalTopic(broker)
 	secret, err := security.Secret(ctx, &security.MTConfigMapSecretLocator{ConfigMap: brokerConfig, UseNamespaceInConfigmap: false}, r.SecretProviderFunc())
```
Comment (creydr) [inline control-plane/pkg/reconciler/broker/broker.go:391]: maybe we can move this to the block starting on line 405, as this is only needed in case of a internal topic  :shrug:

Comment (matzew) [reply control-plane/pkg/reconciler/broker/broker.go:391]: we still have 
```
	if err := r.removeFinalizerSecret(ctx, finalizerSecret(broker), secret); err != nil {
		return err
	}
```

on 448+

Comment (creydr) [reply control-plane/pkg/reconciler/broker/broker.go:391]: ah ok

File: control-plane/pkg/reconciler/broker/broker.go (hunk 1 above)
Comment (matzew) [reply control-plane/pkg/reconciler/broker/broker.go]: yeah, saw that when looking at 405 :-)
