### PR TITLE
Don't reconcile Triggers we don't own

### LINKED ISSUE #211: Don't reconcile Triggers we don't own
**Describe the bug**

We reconcile every trigger in the cluster.

 **Expected behavior**

We reconciler only Trigger that are associated with a Broker that has the `Kafka` broker class.

 **To Reproduce**

Create an MTChannelBasedBroker.

 **Knative release version**
`<= devel`

/assign
/area control-plane
/kind bug

### PR DESCRIPTION
**Pull request by pierDipi**
This PR adds a check to verify that the Trigger we're reconciling
is associated with a Broker with the annotation
`eventing.knative.dev/broker.class` set to `Kafka`.

Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>

Fixes #211 

## Proposed Changes

- Don't reconcile Triggers we don't own

### CODE REVIEW

File: control-plane/pkg/reconciler/trigger/trigger.go [hunk 1]
```diff
@@ -195,8 +196,8 @@ func (r *Reconciler) reconcileKind(ctx context.Context, trigger *eventing.Trigge
 
 		// Actually check if the broker doesn't exist.
 		broker, err = r.EventingClient.EventingV1(). // Note: do not introduce another `broker` variable with `:`
-								Brokers(trigger.Namespace).
-								Get(ctx, trigger.Spec.Broker, metav1.GetOptions{})
+			Brokers(trigger.Namespace).
+			Get(ctx, trigger.Spec.Broker, metav1.GetOptions{})
```
Comment (mattmoor) [inline control-plane/pkg/reconciler/trigger/trigger.go:200]: Format Go code:
```suggestion
								Brokers(trigger.Namespace).
								Get(ctx, trigger.Spec.Broker, metav1.GetOptions{})
```

**Review by mattmoor — COMMENTED** [review]
Produced via:
  `gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
  `goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`

**Review by aliok — APPROVED** [review]
Never touched trigger reconciliation before myself, but reconciling triggers in the brokers' code space seems wrong to me...
Anyway, I know that is not your change and not in the scope of this PR.

/lgtm
/approve

**Comment by aliok** [comment]
Oh, some test needs adaption
```
Errors: 
Error:    FileWatcherTest.shouldReceiveUpdatesOnUpdate » Timeout shouldReceiveUpdatesOnU...
```

**Comment by pierDipi** [comment]
> Never touched trigger reconciliation before myself, but reconciling triggers in the brokers' code space seems wrong to me...

I'm not reconciling them, I need to know when reconciling a Trigger the UUID of the broker and that the broker is a "kafka broker" or we react according the state of the broker (eg we're reconciling a Trigger but the Broker has been deleted), but it's a readonly thing. 
We do a similar thing in eventing: https://github.com/knative/eventing/blob/f2e23101a0e5cd6b64322d5f26d89ae3e4ff539a/pkg/reconciler/mtbroker/trigger/trigger.go#L89-L106
