### PR TITLE
Use broker status annotations to stamp ConfigMap reference

### LINKED ISSUE #1970: metadata.finalizers: Invalid value: name part must be no more than 63 characters
**Describe the bug**
When I create a Knative eventing broker using a configmap with name `ob-46b35be1-0165-441b-9158-a7ec08ad7a97` and namespace `ob-1608dc1f-4139-49c5-ae22-afe73ed807d7` the Broker fails with 
```
 reason: >-
        failed to add finalizer to ConfigMap
        ob-1608dc1f-4139-49c5-ae22-afe73ed807d7/ob-46b35be1-0165-441b-9158-a7ec08ad7a97:
        ConfigMap "ob-46b35be1-0165-441b-9158-a7ec08ad7a97" is invalid:
        metadata.finalizers: Invalid value:
        "kafka.brokers.eventing.knative.dev/ob-1608dc1f-4139-49c5-ae22-afe73ed807d7-ob-46b35be1-0165-441b-9158-a7ec08ad7a97":
        name part must be no more than 63 characters
```

 **Expected behavior**
I think sometimes it is reasonable to use a uuid for a name and a namespace, so I would expect this to work. I think the prefix `kafka.brokers.eventing.knative.dev` is slightly longer than needed. 

 **To Reproduce**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
data:
  auth.secret.ref.name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  bootstrap.servers: REDACTED
  default.topic.partitions: '10'
  default.topic.replication.factor: '3'
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
    namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
```

 **Knative release version**
release-1.1
 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by pierDipi**
Instead of adding a finalizer to the ConfigMap, we can record
the ConfigMap data in the Broker status so that we can re-build
the ConfigMap even when the ConfigMap is deleted first.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes #1970

**Release Note**

```release-note
Support brokers with long namespace and name values.
```

### CODE REVIEW

File: control-plane/pkg/reconciler/broker/broker.go [hunk 1]
```diff
@@ -348,6 +348,7 @@ func (r *Reconciler) finalizeKind(ctx context.Context, broker *eventing.Broker)
 
 	logger.Debug("Topic deleted", zap.String("topic", topic))
 
+	// TODO(pierDipi) remove after some releases (released in 1.4)
```
Comment (matzew) [inline control-plane/pkg/reconciler/broker/broker.go:351]: :+1:

**Comment by matzew** [comment]
```
oc get broker matze-demo-kafka-broker -ojson | jq .status
{
  "address": {
    "url": "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/matze-demo-kafka-broker"
  },
  "annotations": {
    "bootstrap.servers": "my-cluster-kafka-bootstrap.kafka:9092",
    "default.topic.partitions": "10",
    "default.topic.replication.factor": "3"
  },
  "conditions": [
....
```

I do like the solution to capture this - and the in-memory rebuild

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
in case one wants to do another review/test

**Comment by pierDipi** [comment]
since tomorrow is release day, I'm gonna cancel the 'hold', as always feedback is more than welcome!

cc @aliok @devguyio 

/unhold
