### PR TITLE
Thread.sleep changed for Awaitility.await #351

### LINKED ISSUE #351: [data-plane] Remove Thread.sleep in tests and replace with awaitability or similar
**Describe the bug**
We have some tests where we use Thread.sleep. These causes flakyness, we should get rid of these and replace with proper async assertions like awaitability

 **Expected behavior**
Remove Thread.sleep all around our data plane tests

### PR DESCRIPTION
**Pull request by OmarMorales71**
Fixes #351 

## Proposed Changes

-I changed the Thread.sleep in data-plane tests for Awaitility.await

This library (Awaitility has a lot of methods to delay a thread, it can wait for a response or condition).

### CODE REVIEW

**Comment by pierDipi** [comment]
@OmarMorales71, thanks for working on this issue, I left a comment on the issue.

Can you please sign the Google CLA? https://github.com/knative-sandbox/eventing-kafka-broker/pull/478#issuecomment-744196565

/unassign tcnghia

**Comment by OmarMorales71** [comment]
@pierDipi I already sign it :D

**Comment by OmarMorales71** [comment]
@pierDipi I remove one Thread.sleep as you mentioned on the issue. For the other 2, with untilAsserted() the thread is waiting for the assertThat().

File: data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java [hunk 1]
```diff
@@ -98,6 +102,7 @@
   private static KafkaCluster kafkaCluster;
   private static ConsumerDeployerVerticle consumerDeployerVerticle;
   private static ReceiverVerticle receiverVerticle;
+  private static int numResources;
```
Comment (pierDipi) [inline data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java:105]: Move this below `NUM_SYSTEM_VERTICLES`, rename it to `NUM_RESOURCES`, and make it `final` to be consistent.

File: data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java [hunk 2]
```diff
@@ -200,7 +206,10 @@ public void execute(final Vertx vertx, final VertxTestContext context) throws Ex
 
     //TODO(slinkydeveloper) for testing purpose, we need to implement a way to propagate results of reconciliation
     // Or should we use awaitability or similar?
-    Thread.sleep(10000);
+    try {
+      await().atLeast(10, TimeUnit.SECONDS).untilAsserted(() -> assertThat(vertx.deploymentIDs()).hasSize(resource.getEgressesCount()+numResources + NUM_SYSTEM_VERTICLES));
+    }catch(ConditionTimeoutException ex){}
```
Comment (pierDipi) [inline data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java:211]: Remove the try-catch block and propagate the exception.

File: data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java [hunk 3]
```diff
@@ -130,9 +133,9 @@ public void testUnorderedConsumer(final Vertx vertx, final VertxTestContext cont
 
     write(file, contract);
 
-    Thread.sleep(6000); // reduce flakiness
-
-    assertThat(vertx.deploymentIDs()).hasSize(numEgresses + NUM_SYSTEM_VERTICLES);
+    try {
+      await().atMost(6, TimeUnit.SECONDS).untilAsserted(() -> assertThat(vertx.deploymentIDs()).hasSize(numEgresses + NUM_SYSTEM_VERTICLES));
+    }catch(ConditionTimeoutException ex){}
```
Comment (pierDipi) [inline data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java:138]: Remove the try-catch block and propagate the exception.

File: data-plane/tests/pom.xml [hunk 4]
```diff
@@ -105,6 +105,12 @@
       <version>${kafka.version}</version>
       <scope>test</scope>
     </dependency>
+    <dependency>
+      <groupId>org.awaitility</groupId>
+      <artifactId>awaitility</artifactId>
+      <version>3.0.0</version>
+      <scope>test</scope>
+    </dependency>
```
Comment (pierDipi) [inline data-plane/tests/pom.xml:113]: Instead of declaring the version here and in `dispatcher/pom.xml`, can we use a similar technique to `cloudevents-kafka`:

Dependency declaration:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/17e3199118d2a9d47c2bb9319c4b392446503e99/data-plane/pom.xml#L155-L165

Usage:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/17e3199118d2a9d47c2bb9319c4b392446503e99/data-plane/dispatcher/pom.xml#L66-L69

Comment (pierDipi) [reply data-plane/tests/pom.xml:113]: Also, can we use the latest version `4.0.3`? https://mvnrepository.com/artifact/org.awaitility/awaitility/4.0.3

File: data-plane/dispatcher/pom.xml [hunk 5]
```diff
@@ -100,6 +100,12 @@
       <artifactId>mockito-junit-jupiter</artifactId>
       <scope>test</scope>
     </dependency>
+    <dependency>
+      <groupId>org.awaitility</groupId>
+      <artifactId>awaitility</artifactId>
+      <version>3.0.0</version>
+      <scope>test</scope>
+    </dependency>
```
Comment (pierDipi) [inline data-plane/dispatcher/pom.xml:108]: See comment in `tests/pom.xml`.

File: data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java [hunk 6]
```diff
@@ -200,7 +206,10 @@ public void execute(final Vertx vertx, final VertxTestContext context) throws Ex
 
     //TODO(slinkydeveloper) for testing purpose, we need to implement a way to propagate results of reconciliation
     // Or should we use awaitability or similar?
-    Thread.sleep(10000);
+    try {
+      await().atLeast(10, TimeUnit.SECONDS).untilAsserted(() -> assertThat(vertx.deploymentIDs()).hasSize(resource.getEgressesCount()+numResources + NUM_SYSTEM_VERTICLES));
```
Comment (pierDipi) [inline data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java:210]:
```suggestion
      await().atLeast(10, TimeUnit.SECONDS).untilAsserted(() -> assertThat(vertx.deploymentIDs()).hasSize(resource.getEgressesCount() + numResources + NUM_SYSTEM_VERTICLES));
```

**Review by pierDipi — COMMENTED** [review]
Thanks! I left some comments.

File: data-plane/tests/pom.xml (hunk 4 above)
Comment (OmarMorales71) [reply data-plane/tests/pom.xml:113]: Yes, we can.  :D 👍

File: data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java [hunk 7]
```diff
@@ -200,7 +205,7 @@ public void execute(final Vertx vertx, final VertxTestContext context) throws Ex
 
     //TODO(slinkydeveloper) for testing purpose, we need to implement a way to propagate results of reconciliation
     // Or should we use awaitability or similar?
```
Comment (pierDipi) [inline data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java:207]: Now can we remove this `TODO`?

**Review by pierDipi — COMMENTED** [review]
/ok-to-test

File: data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java (hunk 7 above)
Comment (OmarMorales71) [reply data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java:207]: Sure!

**Comment by OmarMorales71** [comment]
@pierDipi I already deleted the TODO 👍

**Review by pierDipi — APPROVED** [review]
Thank you!

/lgtm
/approve
/honk
