### PR TITLE
Fix high memory usage for dispatcher pods

### LINKED ISSUE #2345: [Tracking] High memory usage when using circuit breaker
Tracking issue for https://github.com/vert-x3/vertx-circuit-breaker/issues/58

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes #2345

See for more details https://github.com/vert-x3/vertx-circuit-breaker/issues/58#issuecomment-1161414029 for the testing of this patch.

## Proposed Changes

- Remove vertx-circuit-breaker since it's overkill for our use case
- Move to a custom retry logic

**Release Note**

```release-note
Fix high memory usage for dispatcher pods under load
```

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aavarghese** [comment]
Thanks @pierDipi for sharing your performance test results too!! Will check if this speeds up processing for CE scenario 

/retest-required

**Review by aavarghese — APPROVED** [review]
/lgtm

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java [hunk 1]
```diff
@@ -336,65 +332,10 @@ protected KafkaConsumer<Object, CloudEvent> createConsumer(final Vertx vertx,
...
-          // TODO max failures should be configurable or, at least, set by the control plane
-          .setMaxFailures(egressConfig.getRetry() * 2)
-          .setMaxRetries(egressConfig.getRetry());
-      }
-    }
-    return options;
-  }
-
-  /* package visibility for test */
-  static Function<Integer, Long> computeRetryPolicy(final EgressConfig egress) {
```
Comment (matzew) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java:389]: I have sympathies for moving this out of the factory, to the actual impl of the sender

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java [hunk 2]
```diff
@@ -43,76 +44,96 @@ public final class WebClientCloudEventSender implements CloudEventSender {
...
+        promise.tryFail(e);
       }
-    });
+    }
 
     // Handle closed return value.
-    return future.compose(r -> {
-      if (r == null) {
-       return Future.failedFuture("Sender closed for target="+target);
+    return promise.future().compose(
```
Comment (matzew) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java:118]: I think at the end it's not that big a change, to have our own impl here, instead of a different dependency

**Review by matzew — APPROVED** [review]
/lgtm
/approve

File: control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml [hunk 3]
```diff
@@ -133,6 +133,8 @@ spec:
 
             - name: BROKER_DEFAULT_BACKOFF_DELAY_MS
               value: "1000" # 1 second
+            - name: CHANNEL_DEFAULT_BACKOFF_DELAY_MS
```
[the remark this answers is not in the document]
Comment (aavarghese) [reply control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml:136]: One place - https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/channel/channel.go#L530

**Review by aavarghese — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:aggregate-add-third-party (aggregate-add-third-party) on project data-plane: Execution aggregate-add-third-party of goal org.codehaus.mojo:license-maven-plugin:2.0.0:aggregate-add-third-party failed: Plugin org.codehaus.mojo:license-maven-plugin:2.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:license-maven-plugin:jar:2.0.0 -> org.apache.maven:maven-plugin-api:jar:3.0 -> org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2 -> org.codehaus.plexus:plexus-classworlds:jar:2.2.3: Failed to read artifact descriptor for org.codehaus.plexus:plexus-classworlds:jar:2.2.3: Could not transfer artifact org.codehaus.plexus:plexus-classworlds:pom:2.2.3 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.pom: Connection reset -> [Help 1]
```
/retest-required
